# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160512_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='draft',
            new_name='favourite',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=datetime.datetime(2016, 5, 29, 13, 54, 45, 835000, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
