# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160529_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish', '-updated']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
